### PR TITLE
[#115] Create jenkins jobs for tests & automate configuring servers with ansible

### PR DESCRIPTION
**Pull request by dsummersl**
This automates the process of configuring any new box that integrates
with Jenkins and runs the MyHPOM project.

### CODE REVIEW

**Comment by dsummersl** [comment]
retest this please

**Comment by dsummersl** [comment]
test access

**Comment by dsummersl** [comment]
retest this please

**Comment by cbcunc** [comment]
Should we be committing these keys?

**Comment by dsummersl** [comment]
@cbcunc I encrypted all the keys, but I left the certs unencrypted - should I maybe encrypt those as well (I didn't see the need)?

**Comment by dsummersl** [comment]
(you can tell that the file is encrypted by the `ANSIBLE_VAULT` at the top of the file instead of something more like `---- PRIVATE KEY ----`).

**Pull request merged**
