### PR TITLE
[#145] Legend Contains Other Document Types

### PR DESCRIPTION
**Pull request by philtuskha**
Dane discovered some more Hydroshare specific content.  Commenting out for now until the day when  MYHPOM includes more document types.

### CODE REVIEW

**Review by dsummersl — CHANGES_REQUESTED** [review]
Please revert the whitespace changes that don't affect this change (it'll make future upstream merges a little easier).

**Comment by dsummersl** [comment]
Also a thought for @cbcunc about this legend - Phil's change is to take out the legend completely from the groups/documents listing sections. I think I like this because all the icons in the legend are applicable to types of document and sharing - neither of which seems applicable to myhpom users (all things are private, unless shared, and all things are a 'document' or group of documents).

With that in mind...does it make sense to remove the 'Type' column altogether? It shows the same type/sharing information that isn't going to change from document to document.

types

**Review by cbcunc — DISMISSED** [review]
It seems this merely hides the legends rather than hiding the unused legends. As I greatly anticipate and hope more resource types will be on the way, I would like to keep the legend widget itself, but only expose the legend for Generic Resource, which should be called "Document."

**Comment by cbcunc** [comment]
@dsummersl I'm not for removing the type column now, seeing as how we soon anticipate multiple health oriented resource types.

**Review by dsummersl — APPROVED** [review]
:100:

**Pull request merged**
