### PR TITLE
[MH-131] Reverts SSL proxy hack.

### PR DESCRIPTION
**Pull request by dsummersl**
I logged on to myhpom.edc.renci.org to verify that we are indeed getting the correct header now:

```
# to actually see the traffic on the staging box it didn't have tcpdump installed so I used a public tcpdump image:
docker run -it --net=host corfr/tcpdump -A -s 1000 port 80

...
...
...
X-Forwarded-For: 174.109.109.52
X-Forwarded-For-Port: 41442
X-Forwarded-Proto: https
...
...
...
```

Since staging is the only environment that currently needs this I made this configurable and set it up for staging (at RENCI there is a reverse proxy that terminates the SSL request and sends plain HTTP requests to the MMH server). The new production environment won't (according to Chris, the SSL will be handled by nginx), and when the new staging environment is set up on AWS it won't need this setting either.

### CODE REVIEW

**Comment by kmtracey** [comment]
I don't understand why production won't need this? We still have something in front of us (in this case JUST nginx terminating the SSL), so don't we need that ngninx to set the standard header for us to be able to tell that indeed the original request was secure?

**Comment by dsummersl** [comment]
Oof I think you're right! I'm going to find a way to test this and post the results here.

**Comment by kmtracey** [comment]
I don't understand why production won't need this? We still have something in front of us (in this case JUST nginx terminating the SSL), so don't we need that ngninx to set the standard header for us to be able to tell that indeed the original request was secure?

**Comment by dsummersl** [comment]
I was able to test this locally by adding the following local settings in my .env file:

```
export USE_SSL=true
export USE_NGINX=true
export HOST_SSL_DIR=/tmp/mmh-ssl
export SSL_CERT_DIR=/tmp/mmh-certs
export SSL_CERT_FILE=cert.crt
export SSL_KEY_FILE=cert.key
```

(and decrypting one of the keys in deploy/ssl and putting them in /tmp/mmh-certs as configured above). I could then test various settings, and start up the server using `./hsctl rebuild`.

When running django with gunicorn the requests are WSGIRequests and they respect the `wsgi.url_scheme` value that gunicorn will set based on the X-Forwardarded-Proto header (so we don't need to).

More interesting notes:
 * when USE_SSL=true gunicorn is used rather than runserver

**Review by kmtracey — APPROVED** [review]

**Pull request merged**
